### ISSUE TITLE
[BUG] YouTube Channel is not shown on the property page

### ISSUE THREAD

**Issue by aggre** [dev-protocol/niwa#122]
### Problem subject

- [x] Frontend

### Description

The following address is a YouTube channel that I tokenized on Arbitrum Rinkeby. The asset name is expected to be my YouTube channel name, but it is shown as an empty GitHub repository.

https://arbitrum-rinkeby.niwa.xyz/properties/0xE8e6e0133FFE80754629105248624970A2cC712e

![image](https://user-images.githubusercontent.com/1970283/153799240-352e4165-aeec-4e6b-bfc1-952220611a51.png)

### Expected behavior/contents

My YouTube channel's name with the link (`https://www.youtube.com/channel/${ID}`) should be shown.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stuartwk** [comment]
closed by #123
