### ISSUE TITLE
[BUG] GitHub repo name is linked to Youtube channel name state

### ISSUE THREAD

**Issue by clairefro** [dev-protocol/niwa#146]
### Problem subject

- [x] Other

### Description

The GitHub/Youtube forms seem to be sharing a state, causing the YouTube channel name to be set to the GitHub repo name if the GitHub form has been filled out

Repro:
1. Add a repo name in GitHub form 

![image](https://user-images.githubusercontent.com/9841162/155430528-2701dac9-fc51-41b8-ba4a-efafb6c0784c.png)

2. Go back with "< Select Market" and switch to YouTube form 
![image](https://user-images.githubusercontent.com/9841162/155430768-e91319ae-696c-4da4-8f74-0326bfee6ac2.png)

3. YouTube channel name is set to GitHub repo name

### Expected behavior/contents

Expect: YouTube token form to have an independent input for entering channel name. 

Actual: YouTube channel name is set to GitHub Repo if set in GitHub form

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stuartwk** [comment]
Thanks for filing this bug. Should be resolved now by #165. 
Adds a `reset` method to TokenizeContext, which fires on market select.
