### ISSUE TITLE
[BUG] Update Footer Network Links

### ISSUE THREAD

**Issue by stuartwk** [dev-protocol/niwa#68]
### Problem subject

Footer links aren't working at the moment, since we don't know the domain we'll be using

### Description

Update the footer links once domains are set.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Akira-Taniguchi** [comment]
https://polygon.niwa.xyz/
https://polygon-mumbai.niwa.xyz/
https://arbitrum.niwa.xyz/
https://arbitrum-rinkeby.niwa.xyz/

**Comment by Akira-Taniguchi** [comment]
this is beta version domain

```
https://polygon.niwa-beta.devprotocol.xyz
https://polygon-mumbai.niwa-beta.devprotocol.xyz
https://arbitrum.niwa-beta.devprotocol.xyz
https://arbitrum-rinkeby.niwa-beta.devprotocol.xyz
```
