### ISSUE TITLE
[BUG]Domain and wallet connections are inconsistent.

### ISSUE THREAD

**Issue by Akira-Taniguchi** [dev-protocol/niwa#72]
### Description

The domain is Polygon mumbai, but the wallet runs connected to the Polygon mainnet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stuartwk** [comment]
https://github.com/dev-protocol/niwa/commit/e8b400a327faff0743396ee0064bbe0fab361115 should close all wallet-related bugs. Please create a new issue if you encounter unexpected behavior
