### ISSUE TITLE
[FEATURE] Stake Guard for user DEV Balance

### ISSUE THREAD

**Issue by stuartwk** [dev-protocol/niwa#83]
### Detailed description

Currently, the UI does not check the DEV balance of the connected user.
We should make sure they have enough DEV to stake before submitting the stake.

### Context

Currently, the UI does not check the DEV balance of the connected user.
We should make sure they have enough DEV to stake before submitting the stake.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clairefro** [comment]
I'm working on this

**Comment by clairefro** [comment]
I was unable to find any place that staking happens on Niwa. Is this feature request perhaps for stakes.social? If not, can you help me identify where exactly we need the balance check in Niwa?

**Comment by clairefro** [comment]
Confirmed with Stu that this is the spot that needs the feature: https://github.com/dev-protocol/niwa/tree/main/src/pages/properties/stake
